# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:18
from __future__ import unicode_literals

import app_metrics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauge',
            name='created',
            field=models.DateTimeField(default=app_metrics.models.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='updated',
            field=models.DateTimeField(default=app_metrics.models.now, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='metricitem',
            name='created',
            field=models.DateTimeField(default=app_metrics.models.now, verbose_name='created'),
        ),
    ]
