# Generated by Django 2.0.10 on 2019-02-05 10:06

from django.db import migrations, models
import django.db.models.deletion
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ('app_metrics', '0002_auto_20170608_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauge',
            name='current_value',
            field=models.DecimalField(decimal_places=6, default=decimal.Decimal(0),
                                      max_digits=15, verbose_name='current value'),
        ),
        migrations.AlterField(
            model_name='metricmonth',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='app_metrics.Metric', verbose_name='metric'),
        ),
    ]
